### ISSUE TITLE
One-lined JSON format

### ISSUE THREAD

**Issue by pavel-martynau** [firecampapp/fc-support#17]
If server send JSON in one row, it's got displayed one-lined and it doesn't fit into the message bubble.
<img width="452" alt="Screen Shot 2019-06-06 at 15 06 27" src="https://user-images.githubusercontent.com/1931114/59041966-4b2ee000-8882-11e9-8d78-6905059a28a1.png">

**Comment by Nishchit14** [comment]
shipped with [v0.6.0](https://github.com/firecampapp/fc-support/releases/tag/v0.6.0) 🚀
