### ISSUE TITLE
Feat: Alert for incorrect JSON

### ISSUE THREAD

**Issue by ctfrancia** [firecampapp/fc-support#20]
I spent 5 minutes clicking on 'Emit' button and there was nothing there, then I had to open up the console.log to see that there were a bunch of errors because in my JSON I accidentally put single quotes instead of double quotes. 
Also, finding the github repo to report this was a little more difficult, since on the Chrome extension there is no direct link and had to essentially be a Google ninja to find it.

Sidenote: if I have some time after work today I can see about resolving that issue I reported if you are accepting contributions and PR

**Comment by Nishchit14** [comment]
Oppps... Thanks for sharing the whole story. It's now in our release roadmap.

and we're not open source at this moment, but we are seriously thinking about it. Then you'll be able to contribute to this project.

**Comment by Nishchit14** [comment]
shipped with [v0.6.0](https://github.com/firecampapp/fc-support/releases/tag/v0.6.0) 🚀
