### ISSUE TITLE
[Socket.io] Not support acknowledgements callback?

### ISSUE THREAD

**Issue by Xuhao** [firecampapp/fc-support#24]
It look socket.io's [acknowledgements](https://socket.io/docs/#Sending-and-getting-data-acknowledgements) not support? 

server not **attaching ack callback to event** when emit an event.

**Comment by Xuhao** [comment]
duplicate #4

**Comment by Nishchit14** [comment]
shipped with [v0.6.0](https://github.com/firecampapp/fc-support/releases/tag/v0.6.0) 🚀
