### ISSUE TITLE
Support passing function as argument (aka callback)

### ISSUE THREAD

**Issue by minhpq331** [firecampapp/fc-support#4]
I think it's a great feature to pass a function as an argument when emitting an event. Sometimes we need our event to be responded with callback function

**Comment by annlumia** [comment]
Great request 👍 👍 👍 👍

**Comment by suraj-26p** [comment]
It's required to test existing developed applications. And also to reduce listeners in socket.

**Comment by Nishchit14** [comment]
shipped with [v0.6.0](https://github.com/firecampapp/fc-support/releases/tag/v0.6.0) 🚀
